/**
 * Which topics the examiners actually set, in the order worth revising.
 *
 * GENERATED by tools/pyq_frequency.py from her own past papers — do not edit by
 * hand; re-run the tool.
 *
 * Ranked by how many SITTINGS a topic appears in, then by question count. A
 * topic in all six sittings is one the board reliably asks about; a topic with
 * many questions in one sitting may just have been that paper's theme.
 *
 * This is evidence, not prophecy. It says what has been set, not what will be.
 * Nobody can predict the September paper and the app must never imply it can.
 *
 * Measured across 6 sittings: 2024-07-07, 2024-12-14, 2024-12-15, 2026-02-07, 2026-02-08, 2026-03-01
 */

export interface TopicPriority {
  id: string;
  name: string;
  strand: string;
  /** Questions seen on this topic across all sittings. */
  questions: number;
  /** How many of the sittings included it — the more reliable signal. */
  sittings: number;
}

export const TOPIC_PRIORITY: TopicPriority[] = [
  { id: 'ped_classroom_processes', name: 'Class Room Processes, activities and discourse', strand: 'Pedagogy', questions: 33, sittings: 6 },
  { id: 'ped_evaluation', name: 'Evaluation', strand: 'Pedagogy', questions: 29, sittings: 6 },
  { id: 'geo_globe', name: 'Globe', strand: 'Geography', questions: 18, sittings: 6 },
  { id: 'ped_concept_nature', name: 'Concept & Nature of Social Science/Social Studies', strand: 'Pedagogy', questions: 18, sittings: 6 },
  { id: 'geo_environment', name: 'Environment in its totality: natural and human environment', strand: 'Geography', questions: 15, sittings: 6 },
  { id: 'spl_constitution', name: 'The Constitution', strand: 'Social and Political Life', questions: 15, sittings: 6 },
  { id: 'spl_diversity', name: 'Diversity', strand: 'Social and Political Life', questions: 14, sittings: 6 },
  { id: 'spl_government', name: 'Government', strand: 'Social and Political Life', questions: 14, sittings: 6 },
  { id: 'geo_agriculture', name: 'Agriculture', strand: 'Geography', questions: 9, sittings: 6 },
  { id: 'geo_air', name: 'Air', strand: 'Geography', questions: 9, sittings: 6 },
  { id: 'hist_caste_system', name: 'Challenging the Caste System', strand: 'History', questions: 9, sittings: 6 },
  { id: 'spl_social_justice', name: 'Social Justice and the Marginalised', strand: 'Social and Political Life', questions: 9, sittings: 6 },
  { id: 'geo_planet_earth', name: 'Planet: Earth in the solar system', strand: 'Geography', questions: 7, sittings: 6 },
  { id: 'geo_resources', name: 'Resources: Types-Natural and Human', strand: 'Geography', questions: 9, sittings: 5 },
  { id: 'spl_making_a_living', name: 'Making a Living', strand: 'Social and Political Life', questions: 9, sittings: 5 },
  { id: 'hist_women_reform', name: 'Women and reform', strand: 'History', questions: 8, sittings: 5 },
  { id: 'ped_project_work', name: 'Projects Work', strand: 'Pedagogy', questions: 8, sittings: 5 },
  { id: 'hist_when_where_how', name: 'When, Where and How', strand: 'History', questions: 6, sittings: 5 },
  { id: 'ped_critical_thinking', name: 'Developing Critical thinking', strand: 'Pedagogy', questions: 9, sittings: 4 },
  { id: 'spl_local_government', name: 'Local Government', strand: 'Social and Political Life', questions: 9, sittings: 4 },
  { id: 'geo_human_environment', name: 'Human Environment: settlement, transport and communication', strand: 'Geography', questions: 7, sittings: 4 },
  { id: 'hist_distant_lands', name: 'Contacts with Distant lands', strand: 'History', questions: 6, sittings: 4 },
  { id: 'hist_nationalist_movement', name: 'The Nationalist Movement', strand: 'History', questions: 5, sittings: 4 },
  { id: 'spl_democracy', name: 'Democracy', strand: 'Social and Political Life', questions: 5, sittings: 4 },
  { id: 'spl_judiciary', name: 'The Judiciary', strand: 'Social and Political Life', questions: 5, sittings: 4 },
  { id: 'hist_after_independence', name: 'India After Independence', strand: 'History', questions: 4, sittings: 4 },
  { id: 'hist_rural_life', name: 'Rural Life and Society', strand: 'History', questions: 4, sittings: 4 },
  { id: 'spl_gender', name: 'Unpacking Gender', strand: 'Social and Political Life', questions: 4, sittings: 4 },
  { id: 'hist_company_power', name: 'The Establishment of Company Power', strand: 'History', questions: 5, sittings: 3 },
  { id: 'hist_regional_cultures', name: 'Regional Cultures', strand: 'History', questions: 4, sittings: 3 },
  { id: 'hist_creation_empire', name: 'Creation of an Empire', strand: 'History', questions: 3, sittings: 3 },
  { id: 'hist_new_kings', name: 'New Kings and Kingdoms', strand: 'History', questions: 3, sittings: 3 },
  { id: 'hist_first_farmers', name: 'The First Farmers and Herders', strand: 'History', questions: 3, sittings: 3 },
  { id: 'hist_social_change', name: 'Social Change', strand: 'History', questions: 3, sittings: 3 },
  { id: 'ped_sources', name: 'Sources- Primary & Secondary', strand: 'Pedagogy', questions: 4, sittings: 2 },
  { id: 'geo_water', name: 'Water', strand: 'Geography', questions: 4, sittings: 2 },
  { id: 'ped_problems_teaching', name: 'Problems of teaching Social Science/Social Studies', strand: 'Pedagogy', questions: 3, sittings: 2 },
  { id: 'hist_first_empire', name: 'the first Empire', strand: 'History', questions: 2, sittings: 2 },
  { id: 'hist_architecture', name: 'Architecture', strand: 'History', questions: 2, sittings: 2 },
  { id: 'hist_tribal_societies', name: 'Colonialism and Tribal Societies', strand: 'History', questions: 2, sittings: 2 },
  { id: 'spl_state_government', name: 'State Government', strand: 'Social and Political Life', questions: 2, sittings: 2 },
  { id: 'hist_early_states', name: 'Early States', strand: 'History', questions: 2, sittings: 1 },
];

export const TOTAL_SITTINGS = 6;

/** Priority rank for a topic id; unranked topics sort last. */
export function rankOf(topicId: string | null | undefined): number {
  if (!topicId) return Number.MAX_SAFE_INTEGER;
  const i = TOPIC_PRIORITY.findIndex((t) => t.id === topicId);
  return i === -1 ? Number.MAX_SAFE_INTEGER : i;
}
