const { withAndroidManifest, withDangerousMod, AndroidConfig } = require('expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Make it explicit what survives an app update, an uninstall, and a new phone.
 *
 * WHY THIS PLUGIN EXISTS
 * ----------------------
 * All of her work — attempts, responses, the mistake notebook, her profile —
 * lives in two SQLite files on the device:
 *
 *     files/SQLite/studymate-local.db    attempts, responses, mistakes
 *     databases/RKStorage                AsyncStorage, which holds the profile
 *
 * Android already preserves app data across an UPDATE, so that case works
 * today. But it works by default rather than by decision, and "it happens to
 * be fine" is not a property you want protecting eight months of exam prep.
 * Declaring the rules makes the guarantee explicit and testable, and stops a
 * future manifest change from silently turning it off.
 *
 * WHAT THIS BUYS BEYOND AN UPDATE
 * -------------------------------
 * Android Auto Backup also restores app data when the app is REINSTALLED on a
 * device signed into the same Google account. That is the "get her data back
 * even though she never set a username" case, for free, with no server
 * involved. It is not a guarantee — it needs backup enabled, a Google account,
 * and a successful backup within the last 24h — which is exactly why the
 * optional account exists as the reliable path.
 *
 * WHAT IS DELIBERATELY EXCLUDED
 * -----------------------------
 * `files/SQLite/studymate.db` — the CONTENT bundle. It is a copy of an asset
 * that ships inside the APK, so backing it up would spend her 25MB Google quota
 * storing something the install already provides, and a restored stale copy
 * would be replaced on next launch anyway (openContentDb re-copies when the
 * asset hash changes). Backing it up is pure cost.
 */

const BACKUP_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withBackupRules.js. Android 11 and below.

     ONLY <include> elements. An <exclude> is only meaningful INSIDE an already
     included path, and listing includes already excludes everything else —
     lint rejects the combination with "X is not in an included path", which
     failed the release build. The content bundle stays out because it is
     simply not named here. -->
<full-backup-content>
    <include domain="database" path="RKStorage" />
    <include domain="file" path="SQLite/studymate-local.db" />
    <include domain="sharedpref" path="." />
</full-backup-content>
`;

const DATA_EXTRACTION_RULES = `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withBackupRules.js. Android 12+ replaced
     full-backup-content with this file and ignores the old one, so both ship.

     Same rule as above: includes only. The content bundle
     (SQLite/studymate.db) is excluded by omission — it ships inside the APK,
     so backing it up would spend her Google quota storing something every
     install already has. -->
<data-extraction-rules>
    <cloud-backup>
        <include domain="database" path="RKStorage" />
        <include domain="file" path="SQLite/studymate-local.db" />
        <include domain="sharedpref" path="." />
    </cloud-backup>

    <!-- Phone-to-phone transfer: she has a new phone and expects her
         preparation to come with it. -->
    <device-transfer>
        <include domain="database" path="RKStorage" />
        <include domain="file" path="SQLite/studymate-local.db" />
        <include domain="sharedpref" path="." />
    </device-transfer>
</data-extraction-rules>
`;

function writeXml(platformProjectRoot, name, contents) {
  const dir = path.join(platformProjectRoot, 'app', 'src', 'main', 'res', 'xml');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, name), contents, 'utf8');
}

module.exports = function withBackupRules(config) {
  config = withDangerousMod(config, [
    'android',
    (cfg) => {
      writeXml(cfg.modRequest.platformProjectRoot, 'studymate_backup_rules.xml', BACKUP_RULES);
      writeXml(
        cfg.modRequest.platformProjectRoot,
        'studymate_data_extraction_rules.xml',
        DATA_EXTRACTION_RULES
      );
      return cfg;
    },
  ]);

  return withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$['android:allowBackup'] = 'true';
    app.$['android:fullBackupContent'] = '@xml/studymate_backup_rules';
    app.$['android:dataExtractionRules'] = '@xml/studymate_data_extraction_rules';
    return cfg;
  });
};
